import type { SchemaGraphSemanticsInterface } from '../interfaces/SchemaGraphSemanticsInterface.js';

/**
 * Canonical frozen blank SchemaGraphSemanticsInterface.
 *
 * Used wherever a graph node carries no schema-derived semantics — for example
 * when QuadBackedSchemaGraph dispatchers call `semantics()` on a quad-backed
 * node, or when SchemaGraphSupport encounters a non-record schema node. Both
 * sites previously defined this object independently; this is the single
 * canonical source.
 *
 * The `properties` value is a shared frozen empty Map. `Object.freeze` prevents
 * reassignment of the field; the Map itself is never mutated after construction.
 */
const EMPTY_PROPERTIES: ReadonlyMap<string, never> = new Map<string, never>();

export const EMPTY_SEMANTICS: SchemaGraphSemanticsInterface = Object.freeze({
  'additionalItemsNode': undefined,
  'additionalPropertiesNode': undefined,
  'aliases': [],
  'allOf': [],
  'annotatedEdge': undefined,
  'anyOf': [],
  'asymmetric': false,
  'comment': undefined,
  'complementNode': undefined,
  'computed': false,
  'constValue': undefined,
  'containsNode': undefined,
  'contentEncoding': undefined,
  'contentMediaType': undefined,
  'defaultValue': undefined,
  'definitions': [],
  'dependentRequired': {},
  'dependentSchemaEntries': [],
  'deprecated': false,
  'description': undefined,
  'discriminatorMapping': undefined,
  'discriminatorPropertyName': undefined,
  'disjointWith': undefined,
  'dynamicAnchor': undefined,
  'dynamicRef': undefined,
  'elseNode': undefined,
  'enumValues': undefined,
  'equivalentTo': undefined,
  'examples': undefined,
  'exclusiveMaximum': undefined,
  'exclusiveMinimum': undefined,
  'extensions': {},
  'format': undefined,
  'functional': false,
  'hasConst': false,
  'hasDefault': false,
  'ifNode': undefined,
  'inverseFunctional': false,
  'inverseOf': undefined,
  'iriRef': false,
  'irreflexive': false,
  'itemsNode': undefined,
  'jtConfig': undefined,
  'jtFrozen': false,
  'jtStrict': undefined,
  'language': undefined,
  'maxContains': undefined,
  'maximum': undefined,
  'maxItems': undefined,
  'maxLength': undefined,
  'maxProperties': undefined,
  'minContains': undefined,
  'minimum': undefined,
  'minItems': undefined,
  'minLength': undefined,
  'minProperties': undefined,
  'multipleOf': undefined,
  'oneOf': [],
  'pattern': undefined,
  'patternPropertyEntries': [],
  'prefixItems': [],
  'properties': EMPTY_PROPERTIES,
  'propertyNamesNode': undefined,
  'rdfsDomain': undefined,
  'rdfsRange': undefined,
  'readOnly': false,
  'recursiveAnchor': false,
  'recursiveRef': undefined,
  'ref': undefined,
  'reflexive': false,
  'refTargetNode': undefined,
  'required': [],
  'restrictions': [],
  'schemaAnchor': undefined,
  'schemaDialect': undefined,
  'schemaId': undefined,
  'schemaTypes': [],
  'schemaVocabulary': undefined,
  'symmetric': false,
  'thenNode': undefined,
  'title': undefined,
  'transitive': false,
  'unevaluatedItemsNode': undefined,
  'unevaluatedPropertiesNode': undefined,
  'uniqueItems': false,
  'writeOnly': false
});
