import type {
  GraphErrorCodeType, LoadErrorCodeType, SchemaErrorCodeType
} from '../types/error-codes.js';

export const SchemaErrorCode = {
  'DIALECT_UNSUPPORTED': 'SCHEMA_DIALECT_UNSUPPORTED',
  'DUPLICATE_ANCHOR': 'SCHEMA_DUPLICATE_ANCHOR',
  'MISSING_ID': 'SCHEMA_MISSING_ID',
  'NOT_REGISTERED': 'SCHEMA_NOT_REGISTERED',
  'STRUCTURE_INVALID': 'SCHEMA_STRUCTURE_INVALID',
  'VALIDATOR_MISSING': 'SCHEMA_VALIDATOR_MISSING'
} as const satisfies Record<string, SchemaErrorCodeType>;

export const GraphErrorCode = {
  'ANCHOR_NOT_FOUND': 'ANCHOR_NOT_FOUND',
  'ARTIFACT_INVALID': 'ARTIFACT_INVALID',
  'ARTIFACT_STALE': 'ARTIFACT_STALE',
  'BOOLEAN_SCHEMA_FRAGMENT': 'BOOLEAN_SCHEMA_FRAGMENT',
  'DIALECT_UNSUPPORTED': 'DIALECT_UNSUPPORTED',
  'POINTER_INVALID': 'POINTER_INVALID',
  'POINTER_NOT_FOUND': 'POINTER_NOT_FOUND',
  'POINTER_NOT_SCHEMA': 'POINTER_NOT_SCHEMA',
  'REF_UNRESOLVED': 'REF_UNRESOLVED',
  'VOCABULARY_UNSUPPORTED': 'VOCABULARY_UNSUPPORTED'
} as const satisfies Record<string, GraphErrorCodeType>;

export const LoadErrorCode = {
  'DUPLICATE_ANCHOR': 'LOAD_DUPLICATE_ANCHOR',
  'DUPLICATE_ID': 'LOAD_DUPLICATE_ID',
  'INVALID_JSON': 'LOAD_INVALID_JSON',
  'INVALID_SCHEMA': 'LOAD_INVALID_SCHEMA',
  'IO_FAILURE': 'LOAD_IO_FAILURE',
  'MISSING_ID': 'LOAD_MISSING_ID'
} as const satisfies Record<string, LoadErrorCodeType>;
