import type {
  GraphErrorCodeType,
  InstantiationErrorCodeType,
  LoadErrorCodeType,
  MaterializationErrorCodeType,
  SchemaErrorCodeType
} from '../types/ErrorCodes.js';

export const SchemaErrorCode = {
  'COMPUTED_FN_MISSING': 'COMPUTED_FN_MISSING',
  'COMPUTED_INPUT_FORBIDDEN': 'COMPUTED_INPUT_FORBIDDEN',
  'DIALECT_UNSUPPORTED': 'SCHEMA_DIALECT_UNSUPPORTED',
  'DUPLICATE_ANCHOR': 'SCHEMA_DUPLICATE_ANCHOR',
  'INVALID_INPUT': 'SCHEMA_INVALID_INPUT',
  'MISSING_ID': 'SCHEMA_MISSING_ID',
  'NOT_REGISTERED': 'SCHEMA_NOT_REGISTERED',
  'STRUCTURE_INVALID': 'SCHEMA_STRUCTURE_INVALID',
  'VALIDATOR_MISSING': 'SCHEMA_VALIDATOR_MISSING'
} as const satisfies Record<string, SchemaErrorCodeType>;

export const GraphErrorCode = {
  'ANCHOR_NOT_FOUND': 'ANCHOR_NOT_FOUND',
  'ARTIFACT_INVALID': 'ARTIFACT_INVALID',
  'ARTIFACT_STALE': 'ARTIFACT_STALE',
  'BOOLEAN_SCHEMA_FRAGMENT': 'BOOLEAN_SCHEMA_FRAGMENT',
  'DIALECT_UNSUPPORTED': 'DIALECT_UNSUPPORTED',
  'POINTER_INVALID': 'POINTER_INVALID',
  'POINTER_NOT_FOUND': 'POINTER_NOT_FOUND',
  'POINTER_NOT_SCHEMA': 'POINTER_NOT_SCHEMA',
  'RECURSION_LIMIT': 'RECURSION_LIMIT',
  'REF_UNRESOLVED': 'REF_UNRESOLVED',
  'VOCABULARY_UNSUPPORTED': 'VOCABULARY_UNSUPPORTED'
} as const satisfies Record<string, GraphErrorCodeType>;

export const LoadErrorCode = {
  'DUPLICATE_ANCHOR': 'LOAD_DUPLICATE_ANCHOR',
  'DUPLICATE_ID': 'LOAD_DUPLICATE_ID',
  'INVALID_JSON': 'LOAD_INVALID_JSON',
  'INVALID_SCHEMA': 'LOAD_INVALID_SCHEMA',
  'IO_FAILURE': 'LOAD_IO_FAILURE',
  'MISSING_ID': 'LOAD_MISSING_ID'
} as const satisfies Record<string, LoadErrorCodeType>;

export const InstantiationErrorCode = {
  'EXTRA_FORBIDDEN': 'EXTRA_FORBIDDEN',
  'INSTANTIATION_FAILED': 'INSTANTIATION_FAILED',
  'TRANSFORM_DECODE_FAILED': 'TRANSFORM_DECODE_FAILED'
} as const satisfies Record<string, InstantiationErrorCodeType>;

export const MaterializationErrorCode = {
  'CYCLIC_DATA': 'CYCLIC_DATA',
  'DATA_DEPTH_EXCEEDED': 'DATA_DEPTH_EXCEEDED',
  'MATERIALIZATION_FAILED': 'MATERIALIZATION_FAILED'
} as const satisfies Record<string, MaterializationErrorCodeType>;
