import { OWL } from './IRI.js';

export const RESTRICTION_PREDICATE: Partial<Record<string, string>> = {
  'allValuesFrom': OWL.allValuesFrom,
  'cardinality': OWL.cardinality,
  'hasValue': OWL.hasValue,
  'maxCardinality': OWL.maxCardinality,
  'minCardinality': OWL.minCardinality,
  'someValuesFrom': OWL.someValuesFrom
};

export const OWL_CORE_PREDICATES: ReadonlySet<string> = new Set([
  'owl:AllDifferent',
  'owl:AsymmetricProperty',
  'owl:cardinality',
  'owl:Class',
  'owl:complementOf',
  'owl:DatatypeProperty',
  'owl:distinctMembers',
  'owl:FunctionalProperty',
  'owl:hasValue',
  'owl:intersectionOf',
  'owl:InverseFunctionalProperty',
  'owl:inverseOf',
  'owl:IrreflexiveProperty',
  'owl:maxCardinality',
  'owl:minCardinality',
  'owl:ObjectProperty',
  'owl:oneOf',
  'owl:onProperty',
  'owl:ReflexiveProperty',
  'owl:Restriction',
  'owl:sameAs',
  'owl:SymmetricProperty',
  'owl:TransitiveProperty',
  'owl:unionOf',
  'rdf:first',
  'rdf:nil',
  'rdf:rest',
  'rdf:type',
  'rdf:value',
  'rdfs:comment',
  'rdfs:domain',
  'rdfs:label',
  'rdfs:range',
  'rdfs:subClassOf',
  'rdfs:subPropertyOf'
]);

export const SHACL_CORE_PREDICATES: ReadonlySet<string> = new Set([
  'dash:readOnly',
  'dash:writeOnly',
  'rdfs:comment',
  'rdfs:domain',
  'rdfs:label',
  'rdfs:range',
  'sh:and',
  'sh:class',
  'sh:closed',
  'sh:datatype',
  'sh:description',
  'sh:hasValue',
  'sh:ignoredProperties',
  'sh:in',
  'sh:maxCount',
  'sh:maxExclusive',
  'sh:maxInclusive',
  'sh:maxLength',
  'sh:minCount',
  'sh:minExclusive',
  'sh:minInclusive',
  'sh:minLength',
  'sh:name',
  'sh:node',
  'sh:not',
  'sh:or',
  'sh:path',
  'sh:pattern',
  'sh:property',
  'sh:qualifiedMaxCount',
  'sh:qualifiedMinCount',
  'sh:qualifiedValueShape',
  'sh:targetClass',
  'sh:targetNode'
]);
