export const DEFS_POINTER_PARTS_LENGTH = 3;
export const MIN_PROPERTY_POINTER_PARTS = 3;

export const ID_KEYWORD = '$id';
export const REF_KEYWORD = '$ref';
export const DEFS_KEYWORD = '$defs';
export const SCHEMA_KEYWORD = '$schema';

export const KNOWN_SCHEMA_KEYWORDS = new Set([
  '$anchor',
  '$comment',
  '$defs',
  '$dynamicAnchor',
  '$dynamicRef',
  '$id',
  '$recursiveAnchor',
  '$recursiveRef',
  '$ref',
  '$schema',
  '$vocabulary',
  'additionalItems',
  'additionalProperties',
  'allOf',
  'anyOf',
  'asymmetric',
  'const',
  'contains',
  'contentEncoding',
  'contentMediaType',
  'default',
  'definitions',
  'dependentRequired',
  'dependentSchemas',
  'deprecated',
  'description',
  'discriminator',
  'disjointWith',
  'else',
  'enum',
  'equivalentTo',
  'examples',
  'exclusiveMaximum',
  'exclusiveMinimum',
  'format',
  'functional',
  'if',
  'inverseFunctional',
  'inverseOf',
  'irreflexive',
  'items',
  'jt:alias',
  'jt:computed',
  'jt:config',
  'jt:frozen',
  'jt:strict',
  'maxContains',
  'maximum',
  'maxItems',
  'maxLength',
  'maxProperties',
  'minContains',
  'minimum',
  'minItems',
  'minLength',
  'minProperties',
  'multipleOf',
  'not',
  'oneOf',
  'pattern',
  'patternProperties',
  'prefixItems',
  'properties',
  'propertyNames',
  'rdfs:domain',
  'rdfs:range',
  'readOnly',
  'reflexive',
  'required',
  'symmetric',
  'then',
  'title',
  'transitive',
  'type',
  'unevaluatedItems',
  'unevaluatedProperties',
  'uniqueItems',
  'writeOnly'
]);

export const PRIMITIVE_CONSTRAINT_KEYWORDS = new Set<string>([
  'const',
  'enum',
  'exclusiveMaximum',
  'exclusiveMinimum',
  'format',
  'maximum',
  'maxLength',
  'minimum',
  'minLength',
  'multipleOf',
  'pattern'
]);

export const PRIMITIVE_TYPES = new Set<string>([
  'boolean',
  'integer',
  'number',
  'string'
]);
