export type SchemaErrorCodeType
  = | 'COMPUTED_FN_MISSING'
  | 'COMPUTED_INPUT_FORBIDDEN'
  | 'PROPERTY_CHARACTERISTIC_CONFLICT'
  | 'SCHEMA_DIALECT_UNSUPPORTED'
  | 'SCHEMA_DUPLICATE_ANCHOR'
  | 'SCHEMA_DUPLICATE_ID'
  | 'SCHEMA_DUPLICATE_SHAPE'
  | 'SCHEMA_INVALID_INPUT'
  | 'SCHEMA_MISSING_ID'
  | 'SCHEMA_NOT_REGISTERED'
  | 'SCHEMA_STRUCTURE_INVALID'
  | 'SCHEMA_VALIDATOR_MISSING';

export type GraphErrorCodeType
  = | 'ANCHOR_NOT_FOUND'
  | 'ARTIFACT_INVALID'
  | 'ARTIFACT_STALE'
  | 'BOOLEAN_SCHEMA_FRAGMENT'
  | 'DIALECT_UNSUPPORTED'
  | 'GRAPH_INVALID_RESTRICTION'
  | 'POINTER_INVALID'
  | 'POINTER_NOT_FOUND'
  | 'POINTER_NOT_SCHEMA'
  | 'RECURSION_LIMIT'
  | 'REF_UNRESOLVED'
  | 'VOCABULARY_UNSUPPORTED';

export type LoadErrorCodeType
  = | 'LOAD_DUPLICATE_ANCHOR'
  | 'LOAD_DUPLICATE_ID'
  | 'LOAD_INVALID_JSON'
  | 'LOAD_INVALID_SCHEMA'
  | 'LOAD_IO_FAILURE'
  | 'LOAD_MISSING_ID';

export type InstantiationErrorCodeType = 'EXTRA_FORBIDDEN' | 'INSTANTIATION_FAILED' | 'TRANSFORM_DECODE_FAILED';

export type MaterializationErrorCodeType
  = | 'CYCLIC_DATA'
  | 'MATERIALIZATION_FAILED';
