export type CoercionErrorCodeType = 'COERCION_FAILED';

export type SchemaErrorCodeType
  = | 'COMPUTED_FN_MISSING'
  | 'COMPUTED_INPUT_FORBIDDEN'
  | 'PROPERTY_CHARACTERISTIC_CONFLICT'
  | 'SCHEMA_DIALECT_UNSUPPORTED'
  | 'SCHEMA_DUPLICATE_ANCHOR'
  | 'SCHEMA_DUPLICATE_ID'
  | 'SCHEMA_DUPLICATE_SHAPE'
  | 'SCHEMA_INVALID_INPUT'
  | 'SCHEMA_MISSING_ID'
  | 'SCHEMA_NOT_REGISTERED'
  | 'SCHEMA_STRUCTURE_INVALID'
  | 'SCHEMA_VALIDATOR_MISSING';

export type GraphErrorCodeType
  = | 'ANCHOR_NOT_FOUND'
  | 'ARTIFACT_INVALID'
  | 'ARTIFACT_STALE'
  | 'CURSOR_CARDINALITY'
  | 'DIALECT_UNSUPPORTED'
  | 'GRAPH_INVALID_RESTRICTION'
  | 'INVALID_LANGUAGE_TAG'
  | 'INVALID_PREDICATE_IRI'
  | 'NOT_IMPLEMENTED'
  | 'POINTER_INVALID'
  | 'POINTER_NOT_FOUND'
  | 'POINTER_NOT_SCHEMA'
  | 'RECURSION_LIMIT'
  | 'REF_UNRESOLVED'
  | 'VOCABULARY_UNSUPPORTED';

export type InstantiationErrorCodeType = 'EXTRA_FORBIDDEN' | 'INSTANTIATION_FAILED';

export type TransformErrorCodeType = 'TRANSFORM_DECODE_FAILED' | 'TRANSFORM_ENCODE_FAILED';

export type MaterializationErrorCodeType
  = | 'CYCLIC_DATA'
  | 'INVALID_IRI_VALUE'
  | 'MATERIALIZATION_FAILED'
  | 'MISSING_GRAPH_IRI'
  | 'NON_FINITE_NUMBER';

export type OwlImportErrorCodeType = 'OWL_IMPORT_NOT_IMPLEMENTED';
