/**
 * Renders visualization payloads to HTML documents.
 */

import type { VizPayloadInterface } from '../../interfaces/Viz.js';
import {
  CSS_COLOR_DARK, CSS_COLOR_LIGHT, CSS_COLOR_MID,
  CSS_FONT_WEIGHT_MEDIUM, CSS_FONT_WEIGHT_SEMIBOLD,
  CSS_OPACITY_MUTED, CSS_TRANSITION_DURATION,
  HTML_CHARSET, VIEWPORT_SCALE
} from '../../constants/VISUALIZATION.js';

/**
 * Renders schema graph visualizations as interactive HTML.
 */
export class HtmlRenderer {
  /**
   * Renders a visualization payload to an HTML document.
   *
   * @param payload - The visualization data to render
   * @returns HTML document string
   */
  public render(payload: VizPayloadInterface): string {
    const {
      edges, nodes, schemas
    } = payload;

    const nodesJson = JSON.stringify(nodes);
    const edgesJson = JSON.stringify(edges);
    const schemasJson = JSON.stringify(schemas);

    return `<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="${HTML_CHARSET}">
  <meta name="viewport" content="width=device-width, initial-scale=${VIEWPORT_SCALE}">
  <title>Schema Graph Visualization</title>
  <style>
    * {
      margin: 0;
      padding: 0;
      box-sizing: border-box;
    }

    body {
      font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, Oxygen, Ubuntu, sans-serif;
      background: #f5f5f5;
      color: ${CSS_COLOR_DARK};
    }

    .container {
      max-width: 1200px;
      margin: 0 auto;
      padding: 20px;
    }

    header {
      background: white;
      border-bottom: 1px solid #ddd;
      padding: 20px 0;
      margin-bottom: 20px;
    }

    h1 {
      font-size: 28px;
      font-weight: ${CSS_FONT_WEIGHT_SEMIBOLD};
    }

    .content {
      display: grid;
      grid-template-columns: 1fr 1fr;
      gap: 20px;
    }

    .panel {
      background: white;
      border: 1px solid #ddd;
      border-radius: 8px;
      padding: 20px;
    }

    .panel h2 {
      font-size: 18px;
      margin-bottom: 15px;
      padding-bottom: 10px;
      border-bottom: 2px solid #007bff;
    }

    .schema-list {
      list-style: none;
    }

    .schema-item {
      padding: 10px;
      margin-bottom: 8px;
      background: #f9f9f9;
      border: 1px solid #eee;
      border-radius: 4px;
      cursor: pointer;
      transition: all ${CSS_TRANSITION_DURATION}s;
    }

    .schema-item:hover {
      background: #007bff;
      color: white;
      border-color: #0056b3;
    }

    .schema-id {
      font-weight: ${CSS_FONT_WEIGHT_MEDIUM};
      font-size: 14px;
    }

    .schema-info {
      font-size: 12px;
      margin-top: 4px;
      opacity: ${CSS_OPACITY_MUTED};
    }

    .details-panel {
      grid-column: 1 / -1;
    }

    .detail-content {
      display: none;
      padding-top: 15px;
    }

    .detail-content.active {
      display: block;
    }

    .tabs {
      display: flex;
      gap: 10px;
      margin-bottom: 15px;
      border-bottom: 1px solid #ddd;
    }

    .tab {
      padding: 8px 12px;
      border: none;
      background: none;
      cursor: pointer;
      font-size: 14px;
      border-bottom: 3px solid transparent;
      color: ${CSS_COLOR_MID};
      transition: all ${CSS_TRANSITION_DURATION}s;
    }

    .tab.active {
      color: #007bff;
      border-bottom-color: #007bff;
    }

    .tab-content {
      display: none;
      max-height: 400px;
      overflow-y: auto;
      background: #f9f9f9;
      padding: 10px;
      border-radius: 4px;
      font-family: 'Monaco', 'Courier New', monospace;
      font-size: 12px;
    }

    .tab-content.active {
      display: block;
    }

    .json-content {
      white-space: pre-wrap;
      word-break: break-all;
    }

    footer {
      text-align: center;
      padding: 20px;
      color: ${CSS_COLOR_LIGHT};
      font-size: 12px;
      margin-top: 40px;
    }
  </style>
</head>
<body>
  <header>
    <div class="container">
      <h1>Schema Graph Visualization</h1>
    </div>
  </header>

  <div class="container">
    <div class="content">
      <div class="panel">
        <h2>Schemas</h2>
        <ul class="schema-list" id="schemaList"></ul>
      </div>

      <div class="panel">
        <h2>Relationships</h2>
        <ul class="schema-list" id="relationshipList"></ul>
      </div>

      <div class="panel details-panel">
        <h2>Details</h2>
        <div class="tabs" id="tabs"></div>
        <div id="detailsContent"></div>
      </div>
    </div>
  </div>

  <footer>
    Generated by json-tology schema visualization
  </footer>

  <script>
    const nodes = ${nodesJson};
    const edges = ${edgesJson};
    const schemas = ${schemasJson};

    function renderSchemaList() {
      const list = document.getElementById('schemaList');
      nodes.forEach(node => {
        const item = document.createElement('li');
        item.className = 'schema-item';
        item.innerHTML = \`
          <div class="schema-id">\${node.label}</div>
          <div class="schema-info">\${node.propertyCount} properties</div>
        \`;
        item.addEventListener('click', () => showDetails(node.id));
        list.appendChild(item);
      });
    }

    function renderRelationships() {
      const list = document.getElementById('relationshipList');
      edges.forEach(edge => {
        const sourceLabel = nodes.find(n => n.id === edge.source)?.label || edge.source;
        const targetLabel = nodes.find(n => n.id === edge.target)?.label || edge.target;
        const item = document.createElement('li');
        item.className = 'schema-item';
        item.innerHTML = \`
          <div class="schema-id">\${edge.label}</div>
          <div class="schema-info">\${sourceLabel} → \${targetLabel}</div>
        \`;
        list.appendChild(item);
      });
    }

    function showDetails(schemaId) {
      const schema = schemas.find(s => s.id === schemaId);
      if (!schema) return;

      const container = document.getElementById('detailsContent');
      container.innerHTML = '';

      const tabsContainer = document.getElementById('tabs');
      tabsContainer.innerHTML = '';

      const tabs = [
        { name: 'Schema', content: JSON.stringify(schema.jsonSchema, null, 2) },
        { name: 'TypeScript', content: schema.typescript },
        { name: 'OWL', content: JSON.stringify(schema.owl, null, 2) },
        { name: 'SHACL', content: JSON.stringify(schema.shacl, null, 2) }
      ];

      tabs.forEach((tab, index) => {
        const btn = document.createElement('button');
        btn.className = \`tab\${index === 0 ? ' active' : ''}\`;
        btn.textContent = tab.name;
        btn.addEventListener('click', () => {
          document.querySelectorAll('.tab').forEach(t => t.classList.remove('active'));
          document.querySelectorAll('.tab-content').forEach(c => c.classList.remove('active'));
          btn.classList.add('active');
          document.getElementById(\`tab-\${index}\`).classList.add('active');
        });
        tabsContainer.appendChild(btn);

        const content = document.createElement('div');
        content.id = \`tab-\${index}\`;
        content.className = \`tab-content\${index === 0 ? ' active' : ''}\`;
        content.innerHTML = \`<div class="json-content">\${escapeHtml(tab.content)}</div>\`;
        container.appendChild(content);
      });
    }

    function escapeHtml(text) {
      const div = document.createElement('div');
      div.textContent = text;
      return div.innerHTML;
    }

    renderSchemaList();
    renderRelationships();
    if (nodes.length > 0) showDetails(nodes[0].id);
  </script>
</body>
</html>`;
  }
}
